apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbox-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./apps/controllers/netbox
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-config
