apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: "ServicePrincipal"
      vaultUrl: "https://k8s-homelab.vault.azure.net/"
      authSecretRef:
        clientId:
          name: azure-creds
          key: clientId
          namespace: external-secrets
        clientSecret:
          name: azure-creds
          key: clientSecret
          namespace: external-secrets
        tenantID:
          name: azure-creds
          key: tenantId
          namespace: external-secrets
