apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      tenantId:
        valueFrom:
          secretKeyRef:
            name: azure-secret-creds
            namespace: external-secrets
            key: tenantId
      clientId:
        valueFrom:
          secretKeyRef:
            name: azure-secret-creds
            namespace: external-secrets
            key: clientId
      clientSecret:
        name: azure-secret-creds
        key: clientSecret
      akvUrl: "https://k8s-homelab.vault.azure.net/"
