apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: "ServicePrincipal"
      vaultUrl: "https://k8s-homelab.vault.azure.net/"
      tenantId: "1af28687-4561-4bfa-b57a-a6569f9c88f3"
      authSecretRef:
        clientId:
          name: azure-secret-creds
          key: clientId
          namespace: external-secrets
        clientSecret:
          name: azure-secret-creds
          key: clientSecret
          namespace: external-secrets
