apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: garage-secrets
  namespace: garage
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: garage-secrets
    template:
      type: Opaque
      engineVersion: v2
      data:
        rpc-secret: "{{ .garageRpcSecret }}"
        admin-token: "{{ .garageAdminToken }}"
  data:
    - secretKey: garageRpcSecret
      remoteRef:
        key: garage-rpc-secret
    - secretKey: garageAdminToken
      remoteRef:
        key: garage-admin-token
