apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: homelab-subnet-router
spec:
  hostname: homelab-subnet-router
  subnetRouter:
    advertiseRoutes:
      - "10.0.10.0/24"   # node network
      - "10.244.0.0/16"  # pod CIDR
      - "10.96.0.0/12"   # service CIDR
