apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: operator-oauth
    template:
      type: Opaque
      data:
        client_id: "{{ .tailscaleClientId }}"
        client_secret: "{{ .tailscaleClientSecret }}"
  data:
    - secretKey: tailscaleClientId
      remoteRef:
        key: tailscale-client-id
    - secretKey: tailscaleClientSecret
      remoteRef:
        key: tailscale-client-secret
