apiVersion: v1
kind: Namespace
metadata:
  name: forgejo
  labels:
    app.kubernetes.io/name: forgejo
    app.kubernetes.io/part-of: forgejo
    app.kubernetes.io/managed-by: flux-system
    app.kubernetes.io/instance: forgejo
