apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-config
  namespace: flux-system
spec:
  path: ./infrastructure/configs
  prune: true
  interval: 10m
  timeout: 30m
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-controllers
  postBuild:
    substituteFrom:
      - kind: Secret
        name: azure-secret-creds
        namespace: external-secrets
