apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/base/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: cert-manager
