apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/base/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: external-secrets
