apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/base/metallb-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
