apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/base/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: traefik
  wait: true
  timeout: 2m
  includes:
    - "traefik-crds.yaml"
