apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/base/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
