apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: checkmate-helm-values
  namespace: checkmate
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: checkmate-helm-values
    template:
      type: Opaque
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .jwtSecret }}"
        REFRESH_TOKEN_SECRET: "{{ .refreshTokenSecret }}"
  data:
    - secretKey: jwtSecret
      remoteRef:
        key: checkmate-jwt-secret
    - secretKey: refreshTokenSecret
      remoteRef:
        key: checkmate-refresh-token-secret
