apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-values
  namespace: metallb-system
data:
  values.yaml: |
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - 10.100.0.11-10.100.0.12
