apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.17.1
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: cert-manager
  values:
    # According to the cert-manager Helm chart values, this is new way to enable the CRDs
    crds:
      enabled: true
      keep: true
    prometheus:
      enabled: false
