apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-secrets
  namespace: n8n
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: n8n-secrets
    template:
      type: Opaque
      engineVersion: v2
      data:
        N8N_ENCRYPTION_KEY: "{{ .n8nEncryptionKey }}"
        POSTGRES_PASSWORD: "{{ .n8nPostgresPassword }}"
        DB_POSTGRESDB_PASSWORD: "{{ .n8nPostgresPassword }}"
  data:
    - secretKey: n8nEncryptionKey
      remoteRef:
        key: n8n-encryption-key
    - secretKey: n8nPostgresPassword
      remoteRef:
        key: n8n-postgres-password
