apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forgejo-oauth-credentials
  namespace: forgejo
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: forgejo-oauth-credentials
    template:
      type: Opaque
      engineVersion: v2
      data:
        key: "{{ .clientId }}"
        secret: "{{ .clientSecret }}"
  data:
    - secretKey: clientId
      remoteRef:
        key: forgejo-oauth-client-id
    - secretKey: clientSecret
      remoteRef:
        key: forgejo-oauth-client-secret
