apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forgejo-admin-credentials
  namespace: forgejo
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: forgejo-admin-credentials
    template:
      type: Opaque
      engineVersion: v2
      data:
        username: "{{ .forgejoAdminUser }}"
        password: "{{ .forgejoAdminPassword }}"
  data:
    - secretKey: forgejoAdminUser
      remoteRef:
        key: forgejo-admin-user
    - secretKey: forgejoAdminPassword
      remoteRef:
        key: forgejo-admin-password
