apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials
    template:
      type: Opaque
      engineVersion: v2
      data:
        admin-user: "{{ .grafanaAdminUser }}"
        admin-password: "{{ .grafanaAdminPassword }}"
  data:
    - secretKey: grafanaAdminUser
      remoteRef:
        key: grafana-admin-user
    - secretKey: grafanaAdminPassword
      remoteRef:
        key: grafana-admin-password
