apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [.]

patches:
  - target:
      kind: ConfigMap
      labelSelector: grafana_dashboard=1
    patch: |
      - op: add
        path: /metadata/annotations/grafana_folder
        value: Kubernetes
