apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: netbox-postgresql
  namespace: netbox
spec:
  serviceName: netbox-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: netbox-postgresql
  template:
    metadata:
      labels:
        app: netbox-postgresql
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
      containers:
        - name: postgresql
          image: docker.io/postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: netbox
            - name: POSTGRES_USER
              value: netbox
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: netbox-secrets
                  key: db_password
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "netbox"]
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: nfs-client
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: netbox-postgresql
  namespace: netbox
spec:
  type: ClusterIP
  selector:
    app: netbox-postgresql
  ports:
    - port: 5432
      targetPort: 5432
