apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/part-of: traefik
    app.kubernetes.io/managed-by: flux-system
    app.kubernetes.io/instance: traefik
