# traefik-values.yaml

ports:
  web:
    exposedPort: 80
  websecure:
    exposedPort: 443

api:
  dashboard: true
  insecure: true

ingressRoute:
  dashboard:
    enabled: false # because we will create it in the extraObjects with additional parameters

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  seccompProfile:
    type: RuntimeDefault

extraObjects:
  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: traefik-dashboard
      namespace: traefik
    spec:
      entryPoints:
        - web
        - websecure
      routes:
        - match: PathPrefix(`/dashboard`) || PathPrefix(`/api`)
          kind: Rule
          services:
            - name: api@internal
              kind: TraefikService
