apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-cert
  namespace: authentik
spec:
  secretName: authentik-tls
  dnsNames:
    - auth.local.ruizops.com
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
