apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    template:
      type: Opaque
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .secretKey }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .bootstrapPassword }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .bootstrapToken }}"
        POSTGRES_PASSWORD: "{{ .postgresPassword }}"
  data:
    - secretKey: secretKey
      remoteRef:
        key: authentik-secret-key
    - secretKey: bootstrapPassword
      remoteRef:
        key: authentik-bootstrap-password
    - secretKey: bootstrapToken
      remoteRef:
        key: authentik-bootstrap-token
    - secretKey: postgresPassword
      remoteRef:
        key: authentik-postgres-password
