apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: authentik-secrets
    template:
      type: Opaque
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .secretKey }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .bootstrapPassword }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .bootstrapToken }}"
        POSTGRES_PASSWORD: "{{ .postgresPassword }}"
        AUTHENTIK_POSTGRESQL__HOST: "{{ .postgresHost }}"
        AUTHENTIK_POSTGRESQL__PORT: "{{ .postgresPort }}"
        AUTHENTIK_POSTGRESQL__NAME: "{{ .postgresName }}"
        AUTHENTIK_POSTGRESQL__USER: "{{ .postgresUser }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .postgresPassword }}"
  data:
    - secretKey: secretKey
      remoteRef:
        key: authentik-secret-key
    - secretKey: bootstrapPassword
      remoteRef:
        key: authentik-bootstrap-password
    - secretKey: bootstrapToken
      remoteRef:
        key: authentik-bootstrap-token
    - secretKey: postgresPassword
      remoteRef:
        key: authentik-postgres-password
    - secretKey: postgresHost
      remoteRef:
        key: authentik-postgres-host
    - secretKey: postgresPort
      remoteRef:
        key: authentik-postgres-port
    - secretKey: postgresName
      remoteRef:
        key: authentik-postgres-name
    - secretKey: postgresUser
      remoteRef:
        key: authentik-postgres-user
