apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: grafana
spec:
  secretName: grafana-tls
  dnsNames:
    - grafana.local.ruizops.com
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuers
