apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 5m
  releaseName: grafana
  targetNamespace: grafana
  chart:
    spec:
      chart: grafana
      version: 8.13.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
      hosts:
        - host: grafana.local.ruizops.com
          paths:
            - path: /
              pathType: Prefix
      # tls:
      #   - hosts:
      #       - grafana.example.com
      #     secretName: grafana-tls
