apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netbox-secrets
  namespace: netbox
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: netbox-secrets
    template:
      type: Opaque
      engineVersion: v2
      data:
        secret_key: "{{ .netboxSecretKey }}"
        superuser_password: "{{ .netboxSuperuserPassword }}"
        password: "{{ .netboxSuperuserPassword }}"
        superuser_api_token: "{{ .netboxSuperuserApiToken }}"
        api_token: "{{ .netboxSuperuserApiToken }}"
        db_password: "{{ .netboxDbPassword }}"
        postgres-password: "{{ .netboxDbAdminPassword }}"
        email_password: ""
  data:
    - secretKey: netboxSecretKey
      remoteRef:
        key: netbox-secret-key
    - secretKey: netboxSuperuserPassword
      remoteRef:
        key: netbox-superuser-password
    - secretKey: netboxSuperuserApiToken
      remoteRef:
        key: netbox-superuser-api-token
    - secretKey: netboxDbPassword
      remoteRef:
        key: netbox-db-password
    - secretKey: netboxDbAdminPassword
      remoteRef:
        key: netbox-db-admin-password
