apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: checkmate
  namespace: checkmate
spec:
  interval: 12h
  chart:
    spec:
      chart: charts/helm/checkmate
      sourceRef:
        kind: GitRepository
        name: checkmate
        namespace: checkmate
      interval: 12h
  valuesFrom:
    - kind: Secret
      name: checkmate-helm-values
      valuesKey: JWT_SECRET
      targetPath: secrets.JWT_SECRET
    - kind: Secret
      name: checkmate-helm-values
      valuesKey: REFRESH_TOKEN_SECRET
      targetPath: secrets.REFRESH_TOKEN_SECRET
  values:
    client:
      ingress:
        enabled: false
        host: checkmate.local.ruizops.com

    server:
      protocol: https
      ingress:
        enabled: false
        host: checkmate-api.local.ruizops.com

    secrets:
      CLIENT_HOST: https://checkmate.local.ruizops.com
      DB_CONNECTION_STRING: mongodb://mongodb:27017/uptime_db
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      DB_TYPE: MongoDB
      TOKEN_TTL: 99d
      REFRESH_TOKEN_TTL: 99d
      SYSTEM_EMAIL_ADDRESS: admin@ruizops.com
      SYSTEM_EMAIL_HOST: smtp.example.com
      SYSTEM_EMAIL_PORT: "587"
      SYSTEM_EMAIL_PASSWORD: change_me
      PAGESPEED_API_KEY: change_me

    persistence:
      mongodbSize: 5Gi
      redisSize: 1Gi

  postRenderers:
    - kustomize:
        patches:
          - patch: |
              - op: add
                path: /spec/storageClassName
                value: nfs-database
              - op: add
                path: /metadata/annotations/helm.sh~1resource-policy
                value: keep
            target:
              kind: PersistentVolumeClaim
