apiVersion: v1
kind: Namespace
metadata:
  name: gitea
  labels:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/part-of: gitea
    app.kubernetes.io/managed-by: flux-system
    app.kubernetes.io/instance: gitea
