apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: garage-ui-secrets
  namespace: garage-ui
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: garage-ui-secrets
    template:
      type: Opaque
      engineVersion: v2
      data:
        admin-token: "{{ .garageAdminToken }}"
        auth: "{{ .garageWebUiAuth }}"
  data:
    - secretKey: garageAdminToken
      remoteRef:
        key: garage-admin-token
    - secretKey: garageWebUiAuth
      remoteRef:
        key: garage-webui-auth
