apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Homelab
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: ""
  widgets.yaml: |
    - search:
        provider: google
        target: _blank
  docker.yaml: ""
  proxmox.yaml: ""
