#cloud-config
hostname: vmwks001
fqdn: vmwks001.local.ruizops.com
manage_etc_hosts: true

users:
  - name: ${workstation_username}
    groups: [sudo]
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_public_key}

chpasswd:
  users:
    - name: ${workstation_username}
      password: ${workstation_password}
      type: hash
  expire: false

package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent
  - curl
  - ca-certificates
  - gnupg
  - htop

runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent

timezone: ${timezone}
locale: en_US.UTF-8
