apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-admin-credentials
  namespace: gitea
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: gitea-admin-credentials
    template:
      type: Opaque
      engineVersion: v2
      data:
        username: "{{ .giteaAdminUser }}"
        password: "{{ .giteaAdminPassword }}"
  data:
    - secretKey: giteaAdminUser
      remoteRef:
        key: gitea-admin-user
    - secretKey: giteaAdminPassword
      remoteRef:
        key: gitea-admin-password
