apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-configs
  namespace: flux-system
spec:
  interval: 10m
  path: ./monitoring/base/configs/kube-prometheus-stack/kustomization.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: monitoring
  dependsOn:
    - name: monitoring-controllers
