apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: uptime-kuma-db-credentials
  namespace: uptime-kuma
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: uptime-kuma-db-credentials
    template:
      type: Opaque
      engineVersion: v2
      data:
        mysql-root-password: "{{ .uptimeKumaDbRootPassword }}"
        mysql-password: "{{ .uptimeKumaDbPassword }}"
        db-username: "uptime_kuma"
  data:
    - secretKey: uptimeKumaDbRootPassword
      remoteRef:
        key: uptime-kuma-db-root-password
    - secretKey: uptimeKumaDbPassword
      remoteRef:
        key: uptime-kuma-db-password
