apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 12h
  chart:
    spec:
      chart: uptime-kuma
      version: "4.1.0"
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: uptime-kuma
      interval: 12h
  values:
    volume:
      enabled: true
      storageClassName: nfs-client
      accessMode: ReadWriteOnce

    externalDatabase:
      enabled: true
      type: mariadb
      hostname: uptime-kuma-db
      port: 3306
      database: uptime_kuma
      existingSecret: uptime-kuma-db-credentials
      existingSecretUsernameKey: db-username
      existingSecretPasswordKey: mysql-password

    ingress:
      enabled: false
